[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 %(ENV_VNC_RESOLUTION)sx24 -ac -nolisten tcp
priority=10
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:fluxbox]
command=/usr/bin/fluxbox
priority=20
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -shared -rfbport 5900 -passwd %(ENV_VNC_PASSWORD)s
priority=30
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
priority=40
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openfit]
command=/app/node_modules/.bin/electron /app --no-sandbox
directory=/app
environment=HOME="/data",DISPLAY=":0"
priority=50
autorestart=true
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
